language: node_js
node_js:
- "7.1.0"

script:
- "gulp dev-ci"
- "gulp test"

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"

before_install:
- rvm install 2.3.2

install:
- "npm install"
- "npm install bower -g"
- "bower install"
- "gem install scss_lint"